Added `FlushAsync` function which is called from `CommitAsync` with await keyword
dotnetcore/CAP pull request #1629
Opened 2024-12-26 12:29 UTC by PoteRii

### Description:
Added `FlushAsync` function which is called from `CommitAsync` with await keyword to ensure that multiple messages are produced in correct order from a single transaction

#### Issue(s) addressed:
- https://github.com/dotnetcore/CAP/issues/1626

#### How to test:
Produce multiple messages inside a single transaction and check the order

### Checklist:
- [ ✓] I have tested my changes locally
- [ ] I have added necessary documentation (if applicable)
- [ ] I have updated the relevant tests (if applicable)
- [ ✓] My changes follow the project's code style guidelines

2024-12-31 14:21 UTC, yang-xiaodong requested changes

2024-12-31 14:21 UTC, yang-xiaodong commented on src/DotNetCore.CAP/ICapTransaction.Base.cs
> +    protected virtual async Task FlushAsync()
Why not have Flush() call FlushAsync()?

2024-12-31 14:21 UTC, yang-xiaodong commented on src/DotNetCore.CAP/ICapTransaction.Base.cs
> +#pragma warning disable CA2012 // Use ValueTasks correctly
Remove the `#pragma warning`

2025-01-02 07:51 UTC, PoteRii commented on src/DotNetCore.CAP/ICapTransaction.Base.cs
> +#pragma warning disable CA2012 // Use ValueTasks correctly
removed

2025-01-02 07:51 UTC, PoteRii commented on src/DotNetCore.CAP/ICapTransaction.Base.cs
> +    protected virtual async Task FlushAsync()
changed

2025-01-02 10:26 UTC, yang-xiaodong approved these changes
LGTM, Thanks

2025-01-02 10:26 UTC, merged